---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all
  remote_user: root

  roles:
    - sys-init

- name: install nfs client
  hosts: nfs-common
  remote_user: root

  roles:
    - nfs-common

- name: Configuration drbd,nfs-server,keepalived
  tags:
    - nfs-server-ha
  include: nfs-server-playbook-ha.yml
  when: nfs.ha.enable == true

- name: Configuration drbd,nfs-server,keepalived
  tags:
    - nfs-server
  include: nfs-server-playbook.yml
  when: nfs.ha.enable == false
