---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all
  remote_user: root

  roles:
    - sys-init

- name: install nfs client
  hosts: nfs-common
  remote_user: root

  roles:
    - nfs-common

- name: Configuration drbd,nfs-server,keepalived
  hosts: nfs-server
  remote_user: root
  tags:
    - drbd
  roles:
    - drbd
    - nfs-server
    - keepalived

