---
# vars file for mysql
# src code website--> https://downloads.mysql.com/archives/community/
mysql: mysql-5.6.51.tar.gz
url: https://downloads.mysql.com/archives/get/p/23/file/
mysql_data_path: /data/mysql/
mysql_password: admin
wordpress_db: wordpress
wordpress_user: wordpress
wordpress_password: admin
wordpress_host: "10.0.0.%"
src_store_path: /usr/local/src/
src_code_dir: "{{ mysql.partition('.tar')[0] }}"
install_path: /apps/mysql/
yum_pks:
  - gcc
  - gcc-c++
  - cmake
  - bison
  - zlib-devel
  - libcurl-devel
  - boost-devel
  - ncurses-devel
  - gnutls-devel
  - libxml2-devel
  - openssl-devel
  - libaio-devel
  - perl-Data-Dumper
  - python3-mysql
