- name: yum install Packages
  yum: 
    name: "{{ yum_pks }}" 
    state: present

- name: create mysql user
  user: name=mysql system=yes create_home=no home=/data/mysql shell=/sbin/nologin
- name: create mysql data dir
  file: path={{ mysql_data_path }} state=directory owner=mysql group=mysql
- name: download src code
  unarchive: src={{ url }}{{ mysql }} dest={{ src_store_path }} copy=no

