- name: generate mysql makefile
  shell: 
    chdir: "{{ src_store_path }}{{ src_code_dir }}"
    cmd: "cmake . \
         -DCMAKE_INSTALL_PREFIX={{ install_path }} \
         -DMYSQL_DATADIR={{ mysql_data_path }} \
         -DSYSCONFDIR=/etc/ -DMYSQL_USER=mysql \
         -DWITH_INNOBASE_STORAGE_ENGINE=1 \
         -DWITH_ARCHIVE_STORAGE_ENGINE=1 \
         -DWITH_BLACKHOLE_STORAGE_ENGINE=1 \
         -DWITH_PARTITION_STORAGE_ENGINE=1 \
         -DWITHOUT_MROONGA_STORAGE_ENGINE=1 \
         -DWITH_DEBUG=0 -DWITH_READLINE=1 \
         -DWITH_SSL=system \
         -DWITH_ZLIB=system \
         -DWITH_LIBWRAP=0 \
         -DENABLED_LOCAL_INFILE=1 \
         -DMYSQL_UNIX_ADDR={{ mysql_data_path }}/mysql.sock \
         -DDEFAULT_CHARSET=utf8 \
         -DDEFAULT_COLLATION=utf8_general_ci"
- name: compile mysql
  make:
    chdir: "{{ src_store_path }}{{ src_code_dir }}"
    target: install
    file: "{{ src_store_path }}{{ src_code_dir }}/Makefile"
    #jobs: "{{ ansible_facts.processor_vcpus }}" #启用此项需要将make改为community.general.make,还需要安装插件ansible-galaxy collection install community.general
