- name: add user nginx
  user: name=nginx shell=/sbin/nologin create_home=no
- name: cp php.ini
  shell: 
    cmd: cp "{{ src_store_path }}{{ src_code_path }}/php.ini-production" /etc/php.ini
- name: cp php-fpm.conf
  shell:
    chdir: "{{ install_path }}/etc"
    cmd: cp php-fpm.conf.default php-fpm.conf
- name: cp www.conf
  copy: src=www.conf dest="{{ install_path }}/etc/conf.d/www.conf"
- name: cp php-fpm service
  shell:
    cmd: cp "{{ src_store_path }}{{ src_code_path }}/sapi/fpm/php-fpm.service" /usr/lib/systemd/system/php-fpm.service
- name: create log directory
  file: path="{{ install_path }}/log" state=directory
- name: daemon-reload
  shell: systemctl daemon-reload
- name: start php-fpm service
  service: name=php-fpm state=started enabled=yes
